version: "3.2"
services:
  php-teste-grancursos:
    container_name: php-teste-grancursos
    image: php:7.3.6-fpm
    build:
      context: servico
      dockerfile: Dockerfile
    volumes:
      - ./servico/:/var/www/html
      - ./docker/php/config/extensions.ini:/usr/local/etc/php/conf.d/extensions.ini
    ports:
      - 80:80
    working_dir: /var/www/html/
    networks:
      - network-grancursos
  nginx-webserver-teste-grancursos:
    container_name: nginx-webserver-teste-grancursos
    image: "nginx:1.13.8-alpine"
    volumes:
      - ./servico:/var/www/html/
      - ./docker/nginx/backend/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8022:80"
    depends_on:
      - php-teste-grancursos
    networks:
      - network-grancursos
  vue-teste-grancursos:
    image: node:10
    container_name: vue-teste-grancursos
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./cliente/vue:/home/node/app
    command:
      sh -c 'npm i && npm run serve'
    ports:
      - "8088:8080"
    environment:
      - NODE_ENV=development
    networks:
      - network-grancursos
  frontend-maiscidadao:
    container_name: frontend-maiscidadao
    environment:
      - ENDERECO_API=nginx-webserver-teste-grancursos
    image: "grancursos-teste/cliente"
    build:
      context: cliente/vue
      dockerfile: Dockerfile
      args:
        - ENDERECO_API=nginx-webserver-teste-grancursos
    working_dir: /usr/share/nginx/html
    ports:
      - "4022:80"
    depends_on:
      - php-teste-grancursos
    networks:
      - network-grancursos
  mysql-teste-grancursos:
    container_name: mysql-teste-grancursos
    image: mysql:5.7
#    build:
#      context: docker
#      dockerfile: mysql/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'db_grancursos'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user_grancursos'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'pass_grancursos'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'pass_grancursos'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    volumes:
      - ./database/docker-data/mysql:/var/lib/mysql
      - ./database/:/docker-entrypoint-initdb.d/
    networks:
      - network-grancursos
networks:
  network-grancursos:
    driver: bridge
